# /etc/haproxy/haproxy.cfg
#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option                  http-server-close
    retries                 1
    timeout http-request    10s
    timeout queue           4h
    timeout connect         5s
    timeout client          4h
    timeout server          4h
    timeout http-keep-alive 10s
    timeout check           10s

#---------------------------------------------------------------------
# apiserver frontend which proxys to the masters
#---------------------------------------------------------------------
frontend apiserver
    bind *:{{ haproxy_listen_port }}
    mode tcp
    option tcplog
    default_backend apiserver

#---------------------------------------------------------------------
# round robin balancing for apiserver
#---------------------------------------------------------------------
backend apiserver
    option      httpchk GET /healthz
    http-check  expect status 200
    mode        tcp
    option      ssl-hello-chk
    balance     roundrobin
        {% for haproxy in haproxy_nodes %}
        server {{ haproxy.host_id }} {{ haproxy.host_ip_address }}:{{ haproxy_api_server_src_port }} check
        {% endfor %}

listen stats
    bind *:32700
    stats enable
    stats uri /
    stats hide-version
    stats auth admin:admin
