apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{ kubernetes_control_plane_endpoint }}:{{ kubernetes_control_plane_port }}"
    token: "{{ kubernetes_bootstrap_token }}"
    unsafeSkipCAVerification: true
nodeRegistration:
  kubeletExtraArgs:
    container-runtime: remote
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
    cgroup-driver: systemd
  criSocket: /var/run/containerd/containerd.sock
  name: "{{ inventory_hostname }}"
# ---
# apiVersion: kubeadm.k8s.io/v1beta2
# kind: InitConfiguration
# nodeRegistration:
#   kubeletExtraArgs:
#     container-runtime: remote
#     container-runtime-endpoint: unix:///run/containerd/containerd.sock
#     cgroup-driver: systemd
#   criSocket: /var/run/containerd/containerd.sock
#   name: {{ inventory_hostname }}
# ---
# apiVersion: kubelet.config.k8s.io/v1beta1
# kind: KubeletConfiguration
# cgroupDriver: systemd
